### ISSUE TITLE
where is the parachute brotha ? 

### ISSUE THREAD

**Issue by mayersgamer** [Franc1sco/CS2-Parachute#2]
where is the model of the parachute ? you gotta work hard , plus the movement doesnt increase in air whem you try to left and right movement :*(

**Comment by Franc1sco** [comment]
It should be fixed now.

**Comment by mayersgamer** [comment]
is it for admins only ?

**Comment by y3request** [comment]
> is it for admins only ?

AccessFlag - access required for can use parachuse, leave blank "" for public access.

change the config
{
  "Enabled": true,
  "DecreaseVec": 50,
  "Linear": true,
  "FallSpeed": 100,
  "AccessFlag": "",
  "ConfigVersion": 1
}

**Comment by Franc1sco** [comment]
Added model on the last update.

**Comment by mayersgamer** [comment]
i will try it
