### ISSUE TITLE
Parachute model files

### ISSUE THREAD

**Issue by y3request** [Franc1sco/CS2-Parachute#3]
I dont know if it is supposed to be above me when I am parachuting like it was in 1.6 servers.

But if this is possible, the parachute model is part of the games core files if you can call/spawn it with your plugin

> X:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\pak01.vpk:models\props_survival\parachute\chute.vmdl_c
> vpk:X:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\pak01.vpk:models\weapons\v_parachute.vmdl_c

![Screenshot 2023-12-01 165050](https://github.com/Franc1sco/CS2-Parachute/assets/66896566/ffd740c2-1af7-4521-9452-758c13de6c3d)
I am not sure about coding so possibly wrong terminology, but you may be able to just call "models\props_survival\parachute\chute.vmdl_c" in game
You would have to parent it to the player.
In my opinion you wouldnt need to do the straps either. Would simplify things.

**Comment by y3request** [comment]
If this helps. Exact location in the vpk pack file is
`vpk:C:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\pak01.vpk:models\props_survival\parachute\chute.vmdl_c`

**Comment by Franc1sco** [comment]
added model on the last update
