### ISSUE TITLE
Error in console after installing CS2-Parachute

### ISSUE THREAD

**Issue by lostsoul6** [Franc1sco/CS2-Parachute#8]
Hello @Franc1sco ,

I recently installed the plugin but I notice that after plugin is loaded and a player tries to use parachute in game , console is populated with the following error (every time player presses E one of these errors appear in console ) : 

![error-asli](https://github.com/Franc1sco/CS2-Parachute/assets/127633547/a988ec03-40a8-4035-8c5f-65a01572c155)

Also when holding E , sometimes the parachute model shows and sometimes it doesn't show . It's kind of random and I don't know why sometimes the parachute model works and sometimes doesn't . Can you fix it ?

I have both of the above issues with counterstrikesharp v142 and latest version which is v148 . Issues exists in all versions of CSS .

**Comment by lostsoul6** [comment]
@Franc1sco @RonanLOUARN  I just noticed something in game . If I press E and hold it before I jump , the parachute always opens properly and it shows until I land .

If I press and hold E after I jump or when I'm mid-air , it sometimes shows the model but most times it doesn't show until the exact moment that I'm landing and it shows the parachute at the moment of landing for half a second .

**Comment by Franc1sco** [comment]
I will take a look, thanks for the info. Are you using Windows?

**Comment by lostsoul6** [comment]
@Franc1sco I'm using Linux . You would save my life if you could fix the 2 problems I mentioned in this issue .

**Comment by barlap** [comment]
I also encountered the issue mentioned on linux.

**Comment by Franc1sco** [comment]
Fixed in the latest version.
